### PR TITLE
Add GHA build

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/gliptak/AutoRaise/actions/runs/3246395792

### CODE REVIEW

**Comment by sbmpost** [comment]
@gliptak 
Thank you for your commit. How does this work? Will github build a binary itself which users then can download? I never used github actions ;-)

**Comment by gliptak** [comment]
I providedhttps://github.com/gliptak/AutoRaise/actions/runs/3246395792 above for your review. for now there is an artifact for each (PR) build

as a followup, we can update to upload to https://github.com/sbmpost/AutoRaise/releases on tags

**Comment by sbmpost** [comment]
@gliptak 

Thank you. I think the build step produces an artifact which can be downloaded? (I am writing this from a phone so I can't check at the moment). Note that AutoRaise is intended to be compiled on the host system as Apple always adds a quarantined flag to binaries downloaded from the Internet. Note also that the Makefile sets an additional compilation flag called FOCUS_FIRST depending on the presence of a private api on the host system.

**Comment by gliptak** [comment]
https://github.com/gliptak/AutoRaise/suites/8767965407/artifacts/397633366

**Comment by sbmpost** [comment]
@gliptak 
I am getting a 404 on that last link.

**Comment by gliptak** [comment]
I just checked and the link downloads a ZIP file for me.

**Pull request closed without merging**
